# Generated by Django 3.2.3 on 2021-05-31 10:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(default=1234567890, unique=True, validators=[users.models.mobile_max_len]),
        ),
    ]
